version: '3.0'
services:
  api:
    build:
      context: .
      dockerfile: ${PWD}/docker/api/Dockerfile
    ports:
    - 8888:8888
    environment:
    - PYTHONUNBUFFERED=1
    - FLASK_APP=project/server.py
#    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "flask", "run","--host=0.0.0.0", "-p", "8888"]
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "uvicorn", "src.fastapi_server:app", "--host=0.0.0.0", "--port", "8888"]
    links:
    - elasticsearch
    
  elasticsearch:
    image: elasticsearch:8.3.3
    volumes:
      - elastic-33t-data:/usr/share/elasticsearch/data
    environment:
    - PYTHONUNBUFFERED=1
    - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    - xpack.security.enabled=false
    - discovery.type=single-node
    ports:
    - 9200:9200

  kibana:
    image: kibana:8.3.3
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

volumes:
  elastic-33t-data:
